---
- hosts: all
  gather_facts: no
  user: hi
  tasks:
    - name: mkdir opt/java
      file:
        path: "~/opt/java"
        state: directory
    - name: wget openjdk8
      get_url:
        url: "http://pred.ga/archives/java/java-8-openjdk-armhf.zip"
        dest: "~/opt/java/openjdk8_armhf.zip"

    - name: unzip openjdk8
      unarchive:
        src: "~/opt/java/openjdk8_armhf.zip"
        dest: "~/opt/java/"
        remote_src: True
    
    - name: create link openjdk8
      file:
        src: "~/opt/java/java-8-openjdk-armhf"
        dest: "~/opt/java/openjdk8"
        state: link
        owner: hi
    
    - name: set env var jdk8
      blockinfile:
        dest: "~/.bashrc"
        block: |
          export JAVA_HOME=~/opt/java/openjdk8
        create: yes
        marker: "## ANSIBLE java env"
