---
- hosts: datanodes
  gather_facts: no
  vars:
    uname: hi
  user: "{{ uname }}"
  
  pre_tasks:
    - name: Check hadoop.tar.gz
      stat:
        path: "/home/{{ uname }}/opt/hadoop-1.2.1.tar.gz"
      register: isHadoopZip

    - name: Check hadoop dir
      stat:
        path: "/home/{{ uname }}/opt/hadoop-1.2.1"
      register: isHadoopDir

  tasks:
    - name: wget hadoop-1.2.1
      get_url:
        url: "https://archive.apache.org/dist/hadoop/common/hadoop-1.2.1/hadoop-1.2.1.tar.gz"
        dest: "/home/{{ uname }}/opt/"
      when: not isHadoopZip.stat.exists

    - name: unzip hadoop
      unarchive:
        remote_src: True
        src: "/home/{{ uname }}/opt/hadoop-1.2.1.tar.gz"
        dest: "/home/{{ uname }}/opt/"
      when: not isHadoopDir.stat.exists

    - name: link hadoop
      file:
        src: "/home/{{ uname }}/opt/hadoop-1.2.1"
        dest: "/home/{{ uname }}/opt/hadoop"
        state: link
        owner: "{{ uname }}"
    
    - name: env hadoop
      blockinfile:
        dest: "~/.bashrc"
        block: |
          export HADOOP_HOME=/home/hi/opt/hadoop
          export HADOOP_MAPRED_HOME=$HADOOP_HOME
          export HADOOP_HDFS_HOME=$HADOOP_HOME
          export YARN_HOME=$HADOOP_HOME
          export HADOOP_CONF_DIR=$HADOOP_HOME/conf
          export PATH=$PATH:$HADOOP_HOME/bin:$HADOOP_HOME/sbin
        create: yes
        state: present
        marker: "## ANSIBLE hadoop env"
