---
- hosts: all
  user: hadoop
  gather_facts: no
  vars:
    password: 'hi1234'
    uname: 'hi'
  roles:
    - user-add


- hosts: all
  user: hi
  gather_facts: no
  vars_files:
    - vars/hadoop_conf.yml
  vars:
    uname: 'hi'
    hdconf: "/home/{{ uname }}/opt/hadoop/conf"
  roles:
    - vimrc-conf
    - install-jdk8
    - install-hadoop
    - hadoop-connect


- hosts: namenodes
  user: hi
  gather_facts: no
  vars_files:
    - vars/hadoop_conf.yml
  vars:
    uname: 'hi'
  roles:
    - namenode-pubkey


- hosts: datanodes
  user: hi
  gather_facts: no
  vars_files:
    - vars/hadoop_conf.yml
  vars:
    uname: 'hi'
  roles:
    - propagate-key





# ---
# - hosts: all
#   user: hadoop
#   gather_facts: no
#   vars:
#     password: 'hi1234'
#     uname: 'hi'
#   roles:
#     - user-del