- name: Create User "{{ uname }}"
  become: yes
  user:
    name: "{{ uname }}"
    password: "{{ password | password_hash('sha512') }}"
    shell: "/bin/bash"

- name: mod hi sudo
  become: yes
  command: usermod -aG sudo {{ uname }}

- name: mkdir .ssh
  become: yes
  file:
    path: "/home/{{ uname }}/.ssh"
    state: directory
    mode: '775'
    owner: "{{ uname }}"
    group: "{{ uname }}"

- name: touch authorized_keys
  become: yes
  file:
    path: "/home/{{ uname }}/.ssh/authorized_keys"
    state: touch
    mode: '664'
    owner: "{{ uname }}"
    group: "{{ uname }}"

- name: put pubk
  become: yes
  lineinfile:
    path: "/home/{{ uname }}/.ssh/authorized_keys"
    line: "{{ pubkey }}"